window.combinedStations = {
    'Aarberg': ['Aarberg', 'Aarberg, Post/Bahnhof'],
    'Aarberg, Post/Bahnhof': ['Aarberg', 'Aarberg, Post/Bahnhof'],
    'Seon': ['Seon', 'Seon, Post/Bahnhof'],
    'Seon, Post/Bahnhof': ['Seon', 'Seon, Post/Bahnhof'],
    'Aarberg': ['Aarberg', 'Aarberg, Post/Bahnhof'],
    'Ilanz, Bahnhof/Post': ['Ilanz', 'Ilanz, Bahnhof/Post'],
    'Ilanz': ['Ilanz', 'Ilanz, Bahnhof/Post'],
    'Aarberg, Post/Bahnhof': ['Aarberg', 'Aarberg, Post/Bahnhof'],
    'Andermatt': ['Andermatt', 'Andermatt, Bahnhofplatz'],
    'Andermatt, Bahnhofplatz': ['Andermatt', 'Andermatt, Bahnhofplatz'],
    'Solothurn, Hauptbahnhof': ['Solothurn', 'Solothurn, Hauptbahnhof'],
    'Solothurn': ['Solothurn', 'Solothurn, Hauptbahnhof'],
    'Disentis/Mustér': ['Disentis/Mustér', 'Disentis/Mustér, staziun/posta'],
    'Bern Wankdorf, Bahnhof Nord': ['Bern Wankdorf', 'Bern Wankdorf, Bahnhof Nord'],
    'Bern Wankdorf': ['Bern Wankdorf', 'Bern Wankdorf, Bahnhof Nord'],
    'Rotkreuz': ['Rotkreuz, Bahnhof Nord', 'Rotkreuz', 'Rotkreuz, Bahnhof Süd'],
    'Rotkreuz, Bahnhof Nord': ['Rotkreuz, Bahnhof Nord', 'Rotkreuz', 'Rotkreuz, Bahnhof Süd'],
    'Rotkreuz, Bahnhof Süd': ['Rotkreuz, Bahnhof Nord', 'Rotkreuz', 'Rotkreuz, Bahnhof Süd'],
    'Vignogn, vitg': ['Vignogn, vitg', 'Vignogn, Baselgia'],
    'Vignogn, Baselgia': ['Vignogn, vitg', 'Vignogn, Baselgia'],
	};
